### ISSUE TITLE
Questions on function getGeneralizedForce()

### ISSUE THREAD

**Issue by Fleer-code** [leggedrobotics/raisimLib#31]
Hello. In function getGeneralizedForce(), it returns a vector which contains the torques on each joints. But how can I know the mapping relation between each joints and members in the vector. Does it depend on the link-tree generated by the urdf?

**Comment by jhwangbo** [comment]
The order of joints is the same as the order in the urdf file unless otherwise you explicitly define while you create the instance. You can get the order of the joints and bodies by `getBodyNames()` and `getMovableJointNames()` respectively. Note that some joints have multiple DOF's and they do not correspond to the force 1 to 1. E.g., ball joints have 4 dof's. An example is shown [here](https://slides.com/jeminhwangbo/raisim-manual#/5/9)
